{
  "all": {
    "vars": {
      "ansible_user": "root",
      "ansible_ssh_private_key_file": "~/.ssh/id_ed25519"
    },
    "children": {
      "nomad_servers": {
        "hosts": {
          "server-vm-0": {
            "ansible_host": "192.168.139.123",
            "ansible_port": 22
          },
          "server-vm-1": {
            "ansible_host": "192.168.139.189",
            "ansible_port": 22
          },
          "server-vm-2": {
            "ansible_host": "192.168.139.163",
            "ansible_port": 22
          }
        }
      },
      "nomad_clients": {
        "hosts": {
          "client-vm-0": {
            "ansible_host": "192.168.139.188",
            "ansible_port": 22
          },
          "client-vm-1": {
            "ansible_host": "192.168.139.61",
            "ansible_port": 22
          },
          "client-vm-2": {
            "ansible_host": "192.168.139.214",
            "ansible_port": 22
          }
        }
      },
      "prometheus": {
        "hosts": {
          "prometheus-vm": {
            "ansible_host": "192.168.139.213",
            "ansible_port": 22
          }
        }
      }
    }
  }
}
